### ISSUE TITLE
Crashes in mineclone 2

### ISSUE THREAD

**Issue by Ranko-Saotome** [C-C-Minetest-Server/basket#1]
AsyncErr: Lua: Runtime error from mod 'basket' in callback item_OnPlace(): Runtime error from mod 'basket' in callback node_on_construct(): Runtime error from mod 'basket' in callback node_on_construct(): /home/owner/.minetest/mods/basket/init.lua:17: attempt to index global 'default' (a nil value)
stack traceback:
	/home/owner/.minetest/mods/basket/init.lua:17: in function 'get_formspec'
	/home/owner/.minetest/mods/basket/init.lua:25: in function </home/owner/.minetest/mods/basket/init.lua:20>
	[C]: in function 'set_node'
	...es/mineclone2/mods/ITEMS/REDSTONE/mcl_observers/init.lua:326: in function 'set_node'
	/home/owner/.minetest/mods/basket/init.lua:169: in function </home/owner/.minetest/mods/basket/init.lua:168>
	[C]: in function 'add_node'
	...es/mineclone2/mods/ITEMS/REDSTONE/mcl_observers/init.lua:299: in function 'add_node'
	/app/share/minetest/builtin/game/item.lua:250: in function </app/share/minetest/builtin/game/item.lua:146>
stack traceback:
	[C]: in function 'set_node'
	...es/mineclone2/mods/ITEMS/REDSTONE/mcl_observers/init.lua:326: in function 'set_node'
	/home/owner/.minetest/mods/basket/init.lua:169: in function </home/owner/.minetest/mods/basket/init.lua:168>
	[C]: in function 'add_node'
	...es/mineclone2/mods/ITEMS/REDSTONE/mcl_observers/init.lua:299: in function 'add_node'
	/app/share/minetest/builtin/game/item.lua:250: in function </app/share/minetest/builtin/game/item.lua:146>
stack traceback:
	[C]: in function 'add_node'
	...es/mineclone2/mods/ITEMS/REDSTONE/mcl_observers/init.lua:299: in function 'add_node'
	/app/share/minetest/builtin/game/item.lua:250: in function </app/share/minetest/builtin/game/item.lua:146>

**Comment by LoneWolfHT** [comment]
@Emojigit `default` should probably be a hard dependency
